name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - fsspec
  - s3fs
  - numpy 
  - xarray
  - pandas
  - cartopy
  - matplotlib
  - metpy
  - pyproj
  - seaborn
<<<<<<< HEAD
  - dask
  - zarr
  - python<3.12
=======
  - zarr
  - dask
>>>>>>> dfd2cf13910702beabdebd903e23c6b00c4d3b0d
